name: test and lint
on:
  pull_request:
    types:
      - opened
    branches:    
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install
        run: yarn
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
